# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaleidoscope < Formula
  desc "AI agent front-end design toolkit"
  homepage "https://github.com/callmeradical/kaleidoscope"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/callmeradical/kaleidoscope/releases/download/v0.2.0/ks_0.2.0_darwin_amd64.tar.gz"
      sha256 "97c22ce6946c5c09e55238ca494767cdc2bbb7eefa9952c9821eacdb799602a9"

      define_method(:install) do
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/callmeradical/kaleidoscope/releases/download/v0.2.0/ks_0.2.0_darwin_arm64.tar.gz"
      sha256 "2fd6f93e7b6fd85949ccaf63ad1f2a33767547a5ccd143b7cf9cc6ab060db2b3"

      define_method(:install) do
        bin.install "ks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmeradical/kaleidoscope/releases/download/v0.2.0/ks_0.2.0_linux_amd64.tar.gz"
      sha256 "835e17490343d91131ba5b8c5f725a26b3e97744f05c2d0d40b7e36516b1ad62"
      define_method(:install) do
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmeradical/kaleidoscope/releases/download/v0.2.0/ks_0.2.0_linux_arm64.tar.gz"
      sha256 "23fb122178a35fe0d56f6db729ca6110b1f8949374349c9a0c5acf0348770f6d"
      define_method(:install) do
        bin.install "ks"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ks --version")
  end
end
