# This file was generated by GoReleaser. DO NOT EDIT.
cask "fractal" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_darwin_amd64.tar.gz"
      sha256 "fd05a569c19e1b814835aa3badfcf030d992f475485f6cfbad5f22bb22ecb504"
    end
    on_arm do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_darwin_arm64.tar.gz"
      sha256 "829cea26a1bfcda342eae267722ba83ad62c65d429aef8c08af6b4ab2ddd6734"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_linux_amd64.tar.gz"
      sha256 "5eec8e255504655f25fa51fb67567ac6a8784098abfbed9e57dd39343767697f"
    end
    on_arm do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_linux_arm64.tar.gz"
      sha256 "a48d0afe607a1a44c24a5615c63c773e460db10658e8d0c83f809609fcae4948"
    end
  end

  name "fractal"
  desc "TUI client for Smith autonomous agent orchestration"
  homepage "https://github.com/callmeradical/fractal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fractal"

  # No zap stanza required

end
