# This file was generated by GoReleaser. DO NOT EDIT.
cask "fractal" do
  name "fractal"
  desc "TUI client for Smith autonomous agent orchestration"
  homepage "https://github.com/callmeradical/fractal"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fractal"

  on_macos do
    on_intel do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_darwin_amd64.tar.gz"
      sha256 "ebb244cc625c3e80dabb13f06b38b28bfac7c5a1ab04cf1692e91ae2d63f7638"
    end
    on_arm do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_darwin_arm64.tar.gz"
      sha256 "e88228732dc69dc37d3ba7340ca2be38b5743bc103d05be1bd5907d54f700503"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_linux_amd64.tar.gz"
      sha256 "849aa237462c986bcb9d977ddba736a197df9f8335bffda006af334a9b3fd7c3"
    end
    on_arm do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_linux_arm64.tar.gz"
      sha256 "1405d766c2549e459b1d1096d3c2436d54ae99ae2f0aa10ae08f6ecd2fb3f3fa"
    end
  end

  # No zap stanza required
end
