# This file was generated by GoReleaser. DO NOT EDIT.
cask "fractal" do
  name "fractal"
  desc "TUI client for Smith autonomous agent orchestration"
  homepage "https://github.com/callmeradical/fractal"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fractal"

  on_macos do
    on_intel do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_darwin_amd64.tar.gz"
      sha256 "35fc754e58f1293848c7d5ae1f03f0f0c2c821178fd6ddd581776bdd87052a58"
    end
    on_arm do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_darwin_arm64.tar.gz"
      sha256 "866b6c41ea9f193e3be2f15957f10e330a97f214dfb435f2f94747e9e17e62ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_linux_amd64.tar.gz"
      sha256 "7cf658c83e19e6bc84913b4665adee82ef40bb77d99c552968f5b75942e69994"
    end
    on_arm do
      url "https://github.com/callmeradical/fractal/releases/download/v#{version}/fractal_linux_arm64.tar.gz"
      sha256 "5a52a2719e711ebed23dd00fc5a8c5fb882c718a8ecee173efa90ab8e312a630"
    end
  end

  # No zap stanza required
end
