# This file was generated by GoReleaser. DO NOT EDIT.
cask "ks-cli" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/callmeradical/kaleidoscope/releases/download/v#{version}/ks_#{version}_darwin_amd64.tar.gz"
      sha256 "5dc65e9411ec22b12ac14fce8273183db9712786af99985921f62093b0d0ad99"
    end
    on_arm do
      url "https://github.com/callmeradical/kaleidoscope/releases/download/v#{version}/ks_#{version}_darwin_arm64.tar.gz"
      sha256 "de9e924369fe5ba065385d57f12ff66b7fc5dfaa92ca11038bb93d7525501f10"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/callmeradical/kaleidoscope/releases/download/v#{version}/ks_#{version}_linux_amd64.tar.gz"
      sha256 "0d11325cf57e811c6ec3ebf8bd2dd74ca38b7bf2d3f825236872c3eef28985e8"
    end
    on_arm do
      url "https://github.com/callmeradical/kaleidoscope/releases/download/v#{version}/ks_#{version}_linux_arm64.tar.gz"
      sha256 "72a91da7ecdfdb65b040e512cca0b7b25f164bbdfe74307bb443a7278d24a777"
    end
  end

  name "ks-cli"
  desc "AI agent front-end design toolkit"
  homepage "https://github.com/callmeradical/kaleidoscope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ks"

  # No zap stanza required

end
